# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='am3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_1', models.IntegerField()),
                ('res_2', models.IntegerField()),
                ('res_3', models.IntegerField()),
                ('res_4', models.IntegerField()),
                ('res_5', models.IntegerField()),
                ('res_6', models.IntegerField()),
                ('res_7', models.IntegerField()),
                ('res_8', models.IntegerField()),
                ('res_9', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dlda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_1', models.IntegerField()),
                ('res_2', models.IntegerField()),
                ('res_3', models.IntegerField()),
                ('res_4', models.IntegerField()),
                ('res_5', models.IntegerField()),
                ('res_6', models.IntegerField()),
                ('res_7', models.IntegerField()),
                ('res_8', models.IntegerField()),
                ('res_9', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_1', models.IntegerField()),
                ('res_2', models.IntegerField()),
                ('res_3', models.IntegerField()),
                ('res_4', models.IntegerField()),
                ('res_5', models.IntegerField()),
                ('res_6', models.IntegerField()),
                ('res_7', models.IntegerField()),
                ('res_8', models.IntegerField()),
                ('res_9', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_1', models.IntegerField()),
                ('res_2', models.IntegerField()),
                ('res_3', models.IntegerField()),
                ('res_4', models.IntegerField()),
                ('res_5', models.IntegerField()),
                ('res_6', models.IntegerField()),
                ('res_7', models.IntegerField()),
                ('res_8', models.IntegerField()),
                ('res_9', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='eccf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_1', models.IntegerField()),
                ('res_2', models.IntegerField()),
                ('res_3', models.IntegerField()),
                ('res_4', models.IntegerField()),
                ('res_5', models.IntegerField()),
                ('res_6', models.IntegerField()),
                ('res_7', models.IntegerField()),
                ('res_8', models.IntegerField()),
                ('res_9', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='oopm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_1', models.IntegerField()),
                ('res_2', models.IntegerField()),
                ('res_3', models.IntegerField()),
                ('res_4', models.IntegerField()),
                ('res_5', models.IntegerField()),
                ('res_6', models.IntegerField()),
                ('res_7', models.IntegerField()),
                ('res_8', models.IntegerField()),
                ('res_9', models.IntegerField()),
            ],
        ),
    ]
