# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dlda',
        ),
        migrations.DeleteModel(
            name='dm',
        ),
        migrations.DeleteModel(
            name='ds',
        ),
        migrations.DeleteModel(
            name='eccf',
        ),
        migrations.DeleteModel(
            name='oopm',
        ),
        migrations.AddField(
            model_name='am3',
            name='faculty_nm',
            field=models.CharField(default='Hello', max_length=128),
        ),
    ]
