# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='a',
        ),
    ]
