# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sap_id',
        ),
    ]
