# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_auto_20171007_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='dlda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_nm4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.am3')),
            ],
        ),
        migrations.CreateModel(
            name='dm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_nm3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.am3')),
            ],
        ),
        migrations.CreateModel(
            name='ds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_nm2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.am3')),
            ],
        ),
        migrations.CreateModel(
            name='eccf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_nm5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.am3')),
            ],
        ),
        migrations.CreateModel(
            name='oopm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_nm1', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='appOne.am3')),
            ],
        ),
    ]
