# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_remove_userprofile_sap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.ManyToManyField(to='appOne.Subject'),
        ),
    ]
