# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_userprofile_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subject',
            field=models.ManyToManyField(to='appOne.Subject'),
        ),
    ]
