# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_dlda_dm_ds_eccf_oopm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlda',
            name='faculty_nm4',
        ),
        migrations.RemoveField(
            model_name='dm',
            name='faculty_nm3',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='faculty_nm2',
        ),
        migrations.RemoveField(
            model_name='eccf',
            name='faculty_nm5',
        ),
        migrations.RemoveField(
            model_name='oopm',
            name='faculty_nm1',
        ),
        migrations.RenameField(
            model_name='am3',
            old_name='faculty_nm',
            new_name='facultynm',
        ),
        migrations.DeleteModel(
            name='dlda',
        ),
        migrations.DeleteModel(
            name='dm',
        ),
        migrations.DeleteModel(
            name='ds',
        ),
        migrations.DeleteModel(
            name='eccf',
        ),
        migrations.DeleteModel(
            name='oopm',
        ),
    ]
