# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0004_auto_20181222_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appOne.UserProfile'),
        ),
    ]
