# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0004_auto_20171007_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='am3',
        ),
    ]
