# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0004_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='fac',
        ),
        migrations.AddField(
            model_name='feedback',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
