# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0005_auto_20181222_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='lname',
        ),
        migrations.AddField(
            model_name='feedback',
            name='teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='appOne.TeacherProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.ManyToManyField(related_name='subject_teachers', to='appOne.Subject'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.ManyToManyField(related_name='subject_students', to='appOne.Subject'),
        ),
    ]
