# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appOne', '0005_delete_am3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AM3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.CharField(max_length=250)),
            ],
        ),
    ]
