# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0006_am3'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OOPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.CharField(max_length=250)),
            ],
        ),
    ]
