# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0006_auto_20181222_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
