# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0007_auto_20181222_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.UserProfile'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.Subject'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.TeacherProfile'),
        ),
    ]
