# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0008_auto_20171007_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='am3',
            name='res1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='am3',
            name='res2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dlda',
            name='res1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dlda',
            name='res2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oopm',
            name='res1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oopm',
            name='res2',
            field=models.IntegerField(),
        ),
    ]
