# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0008_auto_20181222_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=5),
        ),
    ]
