# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0009_auto_20171011_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='am3',
            name='res10',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='am3',
            name='res3',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='am3',
            name='res4',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='am3',
            name='res5',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='am3',
            name='res6',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='am3',
            name='res7',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='am3',
            name='res8',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='am3',
            name='res9',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='am3',
            name='res1',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='am3',
            name='res2',
            field=models.IntegerField(default=True),
        ),
    ]
