# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0009_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(default=3),
        ),
    ]
