# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0010_userprofile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(default='1111111111', max_length=10),
            preserve_default=False,
        ),
    ]
