# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 11:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0011_userprofile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
