# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 17:21
from __future__ import unicode_literals

import appOne.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0011_auto_20171011_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='am3',
            name='subject',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='dlda',
            name='subject',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='oopm',
            name='subject',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='oopm',
            name='res1',
            field=models.IntegerField(default=True, validators=[appOne.models.checkfor5]),
        ),
    ]
