# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0014_auto_20171011_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='am3',
            name='res10',
        ),
        migrations.RemoveField(
            model_name='dlda',
            name='res10',
        ),
        migrations.RemoveField(
            model_name='oopm',
            name='res10',
        ),
        migrations.AddField(
            model_name='am3',
            name='sug',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dlda',
            name='sug',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='oopm',
            name='sug',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='oopm',
            name='subject',
            field=models.CharField(default='', max_length=250),
        ),
    ]
