# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0015_auto_20171011_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AM3',
            new_name='Feedback',
        ),
        migrations.DeleteModel(
            name='DLDA',
        ),
        migrations.DeleteModel(
            name='OOPM',
        ),
    ]
